use greeners_core::bspline::BSplineBasis;
use greeners_glm::glm::Family;
use greeners_glm::glm::Link;
use greeners_glm::glmgam::GLMGam;
use ndarray::{Array1, Array2};
use rand::distributions::Distribution;
use rand::{rngs::StdRng, Rng, SeedableRng};
use rand_distr::Normal;

/// GLM-GAM captures a non-linear smooth term on data generated by a
/// sinusoidal function.
#[test]
fn test_gam_smooth_fit() {
    let n = 300;
    let mut rng = StdRng::seed_from_u64(9602);
    let noise = Normal::new(0.0, 0.1).unwrap();

    let mut x_vec = Vec::with_capacity(n);
    let mut y_vec = Vec::with_capacity(n);
    for _ in 0..n {
        let x = rng.gen::<f64>() * 4.0 - 2.0;
        x_vec.push(x);
        y_vec.push((2.0_f64 * x).sin() + noise.sample(&mut rng));
    }
    let y = Array1::from_vec(y_vec);
    let x = Array1::from_vec(x_vec);

    let mut x_linear = Array2::zeros((n, 1));
    x_linear.column_mut(0).fill(1.0);

    let x_smooth = BSplineBasis::generate(&x, 8, 3).unwrap();

    let result = GLMGam::fit(
        &y,
        &x_linear,
        &x_smooth,
        &Family::Gaussian,
        &Link::Identity,
        0.01,
    )
    .unwrap();

    assert!(result.converged);
    // Reconstruct fitted values and check in-sample fit.
    let p = x_linear.ncols();
    let q = x_smooth.ncols();
    let beta = result.params.slice(ndarray::s![..p + q]).to_owned();
    let mut x_full = Array2::zeros((n, p + q));
    x_full.slice_mut(ndarray::s![.., ..p]).assign(&x_linear);
    x_full.slice_mut(ndarray::s![.., p..]).assign(&x_smooth);
    let fitted = x_full.dot(&beta);
    let ss_res: f64 = y
        .iter()
        .zip(fitted.iter())
        .map(|(&y, &f)| (y - f).powi(2))
        .sum();
    let y_mean = y.mean().unwrap();
    let ss_tot: f64 = y.iter().map(|&y| (y - y_mean).powi(2)).sum();
    let r2 = 1.0 - ss_res / ss_tot;
    assert!(r2 > 0.85, "r2 = {}", r2);
    assert!(result.edf > 0.0);
}

/// Input validation.
#[test]
fn test_gam_input_validation() {
    let y = Array1::from_vec(vec![1.0; 10]);
    let x_linear = Array2::from_shape_vec((10, 1), vec![1.0; 10]).unwrap();
    let x_smooth_bad = Array2::from_shape_vec((5, 2), vec![1.0; 10]).unwrap();
    assert!(GLMGam::fit(
        &y,
        &x_linear,
        &x_smooth_bad,
        &Family::Gaussian,
        &Link::Identity,
        0.1
    )
    .is_err());

    assert!(BSplineBasis::generate(&y, 2, 3).is_err()); // df < degree + 1
}
